"""setup images table

Revision ID: 5acf8be277e1
Revises: ffdc0a98111c
Create Date: 2021-09-13 10:44:45.806557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5acf8be277e1'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('imageUrl', sa.TEXT(), nullable=False),
    sa.Column('caption', sa.TEXT(), nullable=False),
    sa.Column('profilePic', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('firstName', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('lastName', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_table('images')
    # ### end Alembic commands ###
