"""added created and updated to images

Revision ID: 588e9769252a
Revises: 5acf8be277e1
Create Date: 2021-09-13 11:07:02.997921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588e9769252a'
down_revision = '5acf8be277e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    # ### end Alembic commands ###
