"""added profilepic


Revision ID: e675ae468ff3
Revises: 666c451e257b
Create Date: 2021-09-16 11:02:32.716444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e675ae468ff3'
down_revision = '666c451e257b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profilePic', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profilePic')
    # ### end Alembic commands ###
